# Generated by Django 4.2.4 on 2023-08-07 12:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0002_allblog_popularblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allblog',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='popularblog',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
